# Change these first
owner: admantium-sg # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Admantium
    url: https://admantium.com
  - name: Lighthouse
    url: https://lighthouse.admantium.com
  - name: Apiblaze
    url: https://apiblaze.admantium.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "1 8 * * 3"

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for my blog and services
  navbar:
    - title: Status
      href: /
